batch:
  accounting-dates:
    from: 2022-01-01
    to: 2022-01-04
  types:
    - daily_transactions
    - daily_client
    - daily_ca
    - daily_sell
    - daily_buy
  entities:
    - London
    - Geneva
    - Singapore
